---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
  replicas: 1
  template:
    spec:
      containers:
        - name: myapp
          envFrom:
            - secretRef:
                name: my-prod-secret
