namespace: production
namePrefix: production-

commonLabels:
  app: myapp1

secretGenerator:
  - name: my-prod-secret
    env: secret.properties

images:
  - name: devopsjourney1/mywebapp
    newName: devopsjourney1/mywebapp
    newTag: 
    
resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - deployment.yaml
